package com.example.demo_zuoye3.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.demo_zuoye3.bean.Smart;

import com.example.demo_zuoye3.db.SmartDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig smartDaoConfig;

    private final SmartDao smartDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        smartDaoConfig = daoConfigMap.get(SmartDao.class).clone();
        smartDaoConfig.initIdentityScope(type);

        smartDao = new SmartDao(smartDaoConfig, this);

        registerDao(Smart.class, smartDao);
    }
    
    public void clear() {
        smartDaoConfig.clearIdentityScope();
    }

    public SmartDao getSmartDao() {
        return smartDao;
    }

}
